Promotion/Promotion/Models/ErrorViewModel.cs
using System;

namespace Promotion.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Promotion/Promotion/Models/MPromotion.cs
using Microsoft.AspNetCore.Http;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Promotion.Models
{
    public class MPromotion
    {
        [Display(Name = "Promo ID")]
        public string promoID { get; set; }
        [Display(Name = "Promo Type")]
        public string promoType { get; set; }
        [Display(Name = "Value Type")]
        public string valueType { get; set; }

        public int valueTotal { get; set; }
        [Display(Name = "Promo Description")]
        public string promoDescription { get; set; }
        [Display(Name = "Promo Duration Start Date")]
        public DateTime promoStartDate { get; set; }
        [Display(Name = "Promo Duration End Date")]
        public DateTime promoEndDate { get; set; }
        [Display(Name = "Item")]
        public string itemUpload { get; set; }
        [Display(Name = "Store")]
        public IEnumerable<Store> Stores { get; set; }



    }
}

Promotion/Promotion/Models/Store.cs
using System.ComponentModel.DataAnnotations;

namespace Promotion.Models
{
    public class Store
    {
        [Key]
        public int storeID { get; set; }

        public string storeName { get; set; }
    }
}

Promotion/Promotion/Controllers/PromotionController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Promotion.Data;
using Promotion.Models;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace Promotion.Controllers
{
    public class PromotionController : Controller
    {
        private readonly ILogger<PromotionController> _logger;
        private readonly StoreDBContext _conn;
        private readonly IWebHostEnvironment _env;
        private string message = string.Empty;
        public PromotionController(ILogger<PromotionController> logger, StoreDBContext conn, IWebHostEnvironment _environment)
        {
            _logger = logger;
            _conn = conn;
            _env = _environment;
        }

        public IActionResult Index()
        {
            MPromotion model = new MPromotion();
            List<Store> stores;
            try
            {
                model.Stores = _conn.Stores.ToList();
            }
            catch (Exception ex) { }
            return View(model);
        }
        [HttpPost]
        public IActionResult UploadFile()
        {

            try
            {
                foreach (var formFile in Request.Form.Files)
                {
                    var fulPath = Path.Combine(_env.ContentRootPath, "Upload", formFile.FileName);
                    using (FileStream fs = System.IO.File.Create(fulPath))
                    {
                        formFile.CopyTo(fs);
                        fs.Flush();
                    }
                    return Json("Upload File Success !");
                }
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            return Json(message);
        }

        [HttpPost]
        public IActionResult Add(MPromotion promotion)
        {
            List<string> items = new List<string>();
            try
            {
                var fullPathOfUpload = Path.Combine(_env.ContentRootPath, "Upload", "Items.txt");
                var fullPathOfResult = Path.Combine(_env.ContentRootPath, "Result", String.Format("{0}.txt", promotion.promoID));
                string[] lines = System.IO.File.ReadAllLines(fullPathOfUpload);

                int counter = 0;
                foreach (string line in lines)
                {
                    if (counter > 0)
                    {
                        items.Add(line);
                    }
                    counter++;
                }
                if (System.IO.File.Exists(fullPathOfResult))
                {
                    System.IO.File.Delete(fullPathOfResult);
                }
                using (StreamWriter sw = System.IO.File.CreateText(fullPathOfResult))
                {
                    sw.WriteLine("FHEAD|{0}|||;", promotion.promoDescription);
                    foreach (var item in items)
                    {
                        sw.WriteLine("FITEM|{0}|{1}|{2}|;", item, promotion.valueType, promotion.valueTotal);
                    }
                    foreach (var store in promotion.Stores)
                    {
                        sw.WriteLine("FITEM|{0}|{1}|{2}|;", store.storeID, promotion.promoStartDate.ToString("yyyymmdd"), promotion.promoEndDate.ToString("yyyymmdd"));
                    }
                    sw.WriteLine("FHEAD||||;");

                    //string value1 = promotion.promoID.Remove(promotion.promoID.Length - 4, 4);
                    //string value2 = (Convert.ToInt32(promotion.promoID.Substring(promotion.promoID.Length - 4, promotion.promoID.Length - 1)) + 1).ToString();


                    message = promotion.promoID.Remove(promotion.promoID.Length - 4, 4) + runningNUmber(Convert.ToInt32(promotion.promoID.Substring(promotion.promoID.Length - 4)) + 1);
                }
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }



            return Json(message);
        }

        public FileResult DownloadFile(string fileName)
        {
            fileName = String.Format("{0}.txt", fileName);
            var fullPathOfResult = Path.Combine(_env.ContentRootPath, "Result", fileName);


            byte[] bytes = System.IO.File.ReadAllBytes(fullPathOfResult);


            return File(bytes, "application/octet-stream", fileName);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        private string runningNUmber(int number)
        {
            string runningNumber = string.Empty;
            if (number < 10)
                runningNumber += "000" + number;
            else if (number < 100)
                runningNumber += "00" + number;
            else if (number < 1000)
                runningNumber += "0" + number;
            else if (number < 10000)
                runningNumber += number.ToString();

            return runningNumber;
        }



    }
}

Promotion/Promotion/Views/Promotion/Index.cshtml
@using Promotion.Models;

@model MPromotion


@{
    ViewData["Title"] = "Index";

}


@{
    List<SelectListItem> listPromo = new List<SelectListItem>();
    listPromo.Add(new SelectListItem { Text = "Simple Discount", Value = "S" });
    listPromo.Add(new SelectListItem { Text = "Completed Discount", Value = "C", Selected = true });
}

@{
    List<SelectListItem> ListValue = new List<SelectListItem>();
    ListValue.Add(new SelectListItem { Text = "Percentage", Value = "P" });
    ListValue.Add(new SelectListItem { Text = "Amout", Value = "A", Selected = true });
}


<div class="col-11 mx-auto pt-0 p-0">
    <div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.promoID)
                    @Html.TextBoxFor(m => m.promoID, new {@class = "form-control", @readonly = "readonly"})
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.promoDescription)
                    @Html.TextBoxFor(m => m.promoDescription, new {@class = "form-control"})

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">

                    @Html.LabelFor(m => m.promoType)
                    @Html.DropDownList("promoType", listPromo, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(m => m.promoStartDate)
                            @Html.TextBoxFor(m => m.promoStartDate, new {@class = "form-control" , @readonly = "readonly"})
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(m => m.promoEndDate)
                            @Html.TextBoxFor(m => m.promoEndDate, new {@class = "form-control" , @readonly = "readonly"})
                        </div>
                    </div>
                </div>

            </div>

        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-9">
                        <div class="form-group">
                            @Html.LabelFor(m => m.valueType)
                            @Html.DropDownList("valueType", ListValue, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            @Html.Label("-","-")
                            @Html.TextBoxFor(m => m.valueTotal, new {@class = "form-control"})
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-9" style="padding-right:0px !important">
                                <div class="form-group">

                                    @Html.LabelFor(m => m.itemUpload)
                                    @Html.TextBox("itemUpload", "Browse file..", new {@class = "form-control" , onclick="javascript:document.getElementById('customFile').click();", @readonly ="readonly" })


                                    @*
                                    <input id="txt" type="text" value="Upload Files" onclick="javascript:document.getElementById('customFile').click();">*@
                                </div>
                            </div>
                            <div class="col-md-3" style="padding-left:0px !important">
                                <div class="form-group">
                                    <input type="file" asp-for="itemUpload" class="btn-primary" style="visibility:hidden;" id="customFile" onchange="getFileName()" />
                                    <button type="button" id="uploadBtn" class="btn btn-primary" onclick="uploadFile()">Upload</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <br />
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="datepicker"></div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.Label("Store","Store")
                    <table id="tblItem" class="table table-bordered">
                        <thead>
                            <tr>
                                <td>@Html.CheckBox("all", false, new {Value="all"})</td>
                                <td></td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Stores)
                            {
                                <tr>
                                    <td>@Html.CheckBox(item.storeID.ToString(), false, new {Value=item.storeID})</td>
                                    <td>@item.storeID</td>
                                    <td>@item.storeName</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

            </div>
            <div class="col-md-6">
                <br />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary w-25" style="border-radius:15px;" onclick="submitData();"><i class="fa fa-home">Submit</i></button>&nbsp;
                <button type="reset" class="btn btn-danger w-25" style="border-radius:15px;" onclick="return cancelData()"><i class="fa fa-home">Cancel</i></button>
            </div>
        </div>

    </div>


</div>
@section Scripts
    {
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <style>
        .dp-highlight .ui-state-default {
            background: #484;
            color: #FFF;
        }

        .ui-datepicker.ui-datepicker-multi {
            width: 100% !important;
        }

        .ui-datepicker-multi .ui-datepicker-group {
            float: none;
        }

        #datepicker {
            width: 100% !important;
            height: 300px;
            overflow-x: scroll;
        }

        .ui-widget {
            font-size: 100%;
            width: 100%;
        }

    </style>
    <script>
        $(function() {
            loadPromoID();
            loadCustomeDatePicker();
            loadCheckBox();
        });

        function loadCustomeDatePicker() {
            $("#promoStartDate").val('');
            $("#promoEndDate").val('');
            $(".datepicker").datepicker({
                minDate: 0,
                numberOfMonths: [1, 1],
                beforeShowDay: function(date) {
                    var date1 = $.datepicker.parseDate($.datepicker._defaults.dateFormat, $("#promoStartDate").val());
                    var date2 = $.datepicker.parseDate($.datepicker._defaults.dateFormat, $("#promoEndDate").val());

                    return [true, date1 && ((date.getTime() == date1.getTime()) || (date2 && date >= date1 && date <= date2)) ? "dp-highlight" : ""];
                },
                onSelect: function(dateText, inst) {
                    var date1 = $.datepicker.parseDate($.datepicker._defaults.dateFormat, $("#promoStartDate").val());
                    var date2 = $.datepicker.parseDate($.datepicker._defaults.dateFormat, $("#promoEndDate").val());
                    var selectedDate = $.datepicker.parseDate($.datepicker._defaults.dateFormat, dateText);

                    if (!date1 || date2) {
                        $("#promoStartDate").val(dateText);
                        $("#promoEndDate").val("");
                        $(this).datepicker();
                    } else if (selectedDate < date1) {
                        $("#promoEndDate").val($("#promoStartDate").val());
                        $("#promoStartDate").val(dateText);
                        $(this).datepicker();
                    } else {
                        $("#promoEndDate").val(dateText);
                        $(this).datepicker();
                    }
                }

            });
        }

        function loadCheckBox() {
            $('#all').click(function(event) {
                if (this.checked) {
                    // Iterate each checkbox
                    $(':checkbox').each(function() {
                        this.checked = true;
                    });
                } else {
                    $(':checkbox').each(function() {
                        this.checked = false;
                    });
                }
            });
        }

        function loadPromoID() {
            $('#promoID').val('P' + (new Date().toJSON().slice(0, 10).replace(/-/g, '')) + '0001')
        }
        function getFileName() {
            $("#itemUpload").val($('input[type=file]').val().split('\\').pop());
        }

        function uploadFile() {
            var files = document.getElementById('customFile').files;// $('#file').files[0];// e.target.files;
            if (files.length > 0) {
                if (window.FormData !== undefined) {
                    var data = new FormData();
                    for (var x = 0; x < files.length; x++) {
                        data.append("file" + x, files[x]);
                    }
                    $.ajax({
                        type: "POST",
                        url: '/Promotion/UploadFile',
                        contentType: false,
                        processData: false,
                        data: data,
                        success: function(result) {
                            alert(result);
                            document.getElementById('customFile').value = null;
                            $('#itemUpload').val('Browse File..')
                        },
                        error: function(xhr, status, p3, p4) {
                            alert('There is an issue when uploading data !');
                        }
                    });
                } else {
                    alert("NOT FOR IE OKAY ?!");
                }
            }
        }

        function submitData() {
            var items = [];
            $('#tblItem > tbody  > tr').each(function(index, tr) {
                var checkBox = $(tr).children().find('input');
                if (checkBox.prop("checked")) {
                    const obj = { storeID: checkBox.val(), storeName: "" };
                    items.push(obj);
                }
            });



            var data = {

                promoID: $('#promoID').val(),
                promoDescription: $('#promoDescription').val(),
                promoType: $('#promoType').val(),
                promoStartDate: $('#promoStartDate').val(),
                promoEndDate: $('#promoEndDate').val(),
                valueType: $('#valueType').val(),
                valueTotal: $('#valueTotal').val(),
                Stores: items

            };

            $.ajax({
                type: "POST",
                data: data,
                url: '/Promotion/Add',
            }).done(function(res) {
                $('#promoID').val(res);
                window.location = window.location.origin + '/Promotion/DownloadFile?fileName=' +res;
            });
        }

        function cancelData() {
            $(".datepicker").datepicker("destroy");
            loadCustomeDatePicker();
            $(':checkbox').each(function() {
                this.checked = false;
            });
            $('#valueTotal').val("0");
            $('#promoDescription').val("");
            $('#promoDescription').val("");
            document.getElementById('customFile').value = null;
            $('#itemUpload').val('Browse File..')
            return true;
        }

    </script>
}

Promotion/Promotion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Promotion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <div class="row">
        <div class="col-2 bg-orange">
            <div class="row" style="height:150px;">
                <div class="col-md-12" style="text-align:center; margin-top:50px;">
                    <img width="75" height="75" style="border:2px; border-radius:50px;" src="https://www.bing.com/th?id=A8b7ffe54044ce2871ae36c2d3aa8f441&w=124&h=168&c=7&o=6&pid=SANGAM" >
                </div>
            </div>
            <div class="row">
                <div class="col-md-12" style="margin-left:20px;">
                    <strong>
                        <h2>Home Promotion</h2>
                    </strong>
                </div>

            </div>

        </div>
        <div class="col-10 " style="padding-left:0px !important;">
            <nav class="bg-mocca navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
                <div class="container ">

                    <a class="navbar-brand " asp-area="" asp-controller="Promotion" asp-action="Index">Promotion</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Promotion" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container">
                    @RenderBody()
             
            </div>

        </div>
    </div>



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Promotion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>